const firstNames = [
    // Existing English/Caucasian Names (Consolidated for brevity - keep all original names)
    "Aaron", "Abigail", "Adam", "Adrian", "Aiden", "Alan", "Albert", "Alex", "Alexander", "Alexandra", "Alice", "Alicia", "Allison", "Alyssa", "Amanda", "Amber", "Amelia", "Amy", "Andrea", "Andrew", "Angela", "Angelina", "Anna", "Anthony", "Arthur", "Ashley", "Aubrey", "Austin", "Autumn", "Ava", "Avery",
    "Barbara", "Barry", "Benjamin", "Bernard", "Beth", "Beverly", "Bianca", "Blake", "Bradley", "Brandon", "Brenda", "Brian", "Brianna", "Brittany", "Brody", "Brooke", "Bruce", "Bryan", "Caleb", "Cameron", "Carl", "Carlos", "Carol", "Caroline", "Carter", "Cassandra", "Catherine", "Cecilia", "Chad", "Charles", "Charlotte", "Cheryl", "Christian", "Christine", "Christopher", "Claire", "Clarence", "Clara", "Clifford", "Colin", "Colton", "Connor", "Courtney", "Craig", "Crystal", "Cynthia",
    "Daniel", "Danielle", "David", "Deborah", "Declan", "Delilah", "Dennis", "Derek", "Derrick", "Diana", "Diane", "Dominic", "Donald", "Donna", "Doris", "Dorothy", "Douglas", "Dylan",
    "Edward", "Elaine", "Eleanor", "Elena", "Eli", "Elijah", "Eliza", "Elizabeth", "Ella", "Ellen", "Ellie", "Emily", "Emma", "Eric", "Erica", "Erik", "Erin", "Ethan", "Eugene", "Evan", "Evelyn",
    "Faith", "Felicia", "Felix", "Fiona", "Francis", "Frank", "Frederick", "Gabriel", "Gabriella", "Gage", "Garrett", "Gary", "George", "Georgia", "Gerald", "Gina", "Giovanni", "Grace", "Grant", "Gregory", "Gwendolyn",
    "Hannah", "Harold", "Hayden", "Heather", "Henry", "Herbert", "Holly", "Howard", "Hudson", "Hunter",
    "Ian", "Isaac", "Isabella", "Isabelle", "Isaiah", "Ivan", "Ivy",
    "Jack", "Jackson", "Jacob", "Jacqueline", "Jade", "Jake", "James", "Jamie", "Jared", "Jasmine", "Jason", "Jasper", "Jayden", "Jeffrey", "Jenna", "Jennifer", "Jeremiah", "Jeremy", "Jessica", "Jill", "Joan", "Joanna", "Jocelyn", "Joel", "John", "Johnny", "Jonathan", "Jordan", "Joseph", "Joshua", "Joy", "Joyce", "Juan", "Judith", "Judy", "Julia", "Julian", "Julie", "Justin", "Kaitlyn", "Karen", "Katherine", "Kathleen", "Katie", "Kayla", "Keith", "Kelly", "Kenneth", "Kevin", "Kimberly", "Kurt", "Kyle",
    "Landon", "Laura", "Lauren", "Lawrence", "Leah", "Leo", "Leonard", "Leslie", "Liam", "Lillian", "Lily", "Linda", "Logan", "Lucas", "Lucy", "Luis", "Luke", "Lydia",
    "Madeline", "Madison", "Makayla", "Marcus", "Margaret", "Maria", "Mariah", "Marie", "Marilyn", "Mario", "Mark", "Marshall", "Martha", "Martin", "Mary", "Mason", "Matthew", "Megan", "Melanie", "Melissa", "Michael", "Michelle", "Miguel", "Mikayla", "Miles", "Miriam", "Molly", "Monica", "Morgan",
    "Nancy", "Naomi", "Natalie", "Nathan", "Nathaniel", "Neil", "Nicholas", "Nicole", "Nina", "Noah", "Nolan", "Norman", "Nora",
    "Oliver", "Olivia", "Omar", "Oscar", "Owen",
    "Paige", "Pamela", "Patricia", "Patrick", "Paul", "Paula", "Penelope", "Peter", "Philip", "Phoebe", "Preston", "Priscilla",
    "Quentin", "Quincy", "Quinn",
    "Rachel", "Ralph", "Randall", "Raymond", "Rebecca", "Reese", "Regina", "Richard", "Riley", "Robert", "Robin", "Roger", "Ronald", "Rose", "Ross", "Russell", "Ruth", "Ryan",
    "Samantha", "Samuel", "Sandra", "Sara", "Sarah", "Savannah", "Scott", "Sean", "Sebastian", "Selena", "Serena", "Seth", "Shane", "Shannon", "Shawn", "Shelby", "Shirley", "Sierra", "Simon", "Sophia", "Spencer", "Stanley", "Stephanie", "Stephen", "Steven", "Stuart", "Susan", "Sydney",
    "Taylor", "Tessa", "Theodore", "Theresa", "Thomas", "Timothy", "Tina", "Todd", "Tracy", "Travis", "Trevor", "Tristan", "Troy", "Tyler", "Tyson",
    "Valerie", "Vanessa", "Veronica", "Victor", "Victoria", "Vincent", "Violet", "Virginia",
    "Walter", "Warren", "Wayne", "Wesley", "William", "Willow", "Wyatt",
    "Xander", "Xavier",
    "Yasmin", "Yvette",
    "Zachary", "Zane", "Zoe",
  
    // Hispanic/South American First Names
    "Alejandro", "Sofia", "Mateo", "Isabella", "Santiago", "Valentina", "Matias", "Camila", "Diego", "Valeria", "Emiliano", "Renata", "Sebastian", "Antonella", "Joaquin", "Mariana", "Daniel", "Gabriela", "Nicolas", "Luciana", "Samuel", "Ximena", "Thiago", "Martina", "Benjamín", "Catalina", "Leonardo", "Emma",  "Joaquín", "Emilia", "Gabriel", "Victoria", "Lucas", "Julieta", "Tomas", "Agustina", "Martin", "Josefina", "Felipe", "Mia", "David", "Florencia", "Juan Pablo", "Abril", "Francisco", "Zoe", "Bruno", "Paulina", "Angel", "Elena", "Alex", "Guadalupe", "Javier", "Andrea", "Manuel", "Valeria", "Ricardo", "Carolina", "Antonio", "Fernanda", "Jorge", "Daniela", "Pedro", "Paola", "Luis", "Adriana", "Carlos", "Alejandra", "Miguel", "Natalia", "Rafael", "Isabel", "Jose", "Maria", "Jesus", "Ana", "Pablo", "Carmen", "Eduardo", "Rosa", "Arturo", "Teresa", "Fernando", "Patricia", "Raul", "Martha", "Ramon", "Monica", "Enrique", "Laura", "Sergio", "Sandra",
    "Andrés", "Lucía", "Óscar", "Lorena", "Gustavo", "Silvia", "Roberto", "Gloria", "Hector", "Cristina",
  
    // German First Names
    "Maximilian", "Sophie", "Alexander", "Marie", "Paul", "Leonie", "Elias", "Anna", "Felix", "Lena", "Henry", "Mia", "Louis", "Emilia", "Lukas", "Johanna", "Jonas", "Clara", "Leon", "Emma", "Noah", "Hannah", "Tim", "Lina", "Finn", "Sophia", "Julian", "Mila", "Ben", "Lara", "Tom", "Ella", "Niklas", "Lea", "Jakob", "Nele", "David", "Lotta", "Jan", "Lisa", "Philipp", "Greta", "Maxim", "Maja", "Fabian", "Frieda", "Matteo", "Hanna", "Anton", "Mathilda", "Moritz", "Amelie", "Simon", "Ida", "Jonathan", "Luisa", "Oscar", "Sarah", "Erik", "Pia", "Johannes", "Mara", "Frederik", "Julia", "Leonard", "Leni", "Vincent", "Lilly", "Karl", "Paula", "Theodor", "Jana", "Jannik", "Laura", "Constantin", "Elisa", "Valentin", "Emily", "Mika", "Melina", "Florian", "Alina", "Arthur", "Charlotte", "Emil", "Mira", "Julius", "Helena", "Adrian", "Josephine",
    "Benedikt", "Isabella", "Richard", "Marlene", "Oskar", "Eva",
  
  ];
  
  const lastNames = [
    // Existing English/Caucasian Last Names (Consolidated - keep all original names)
    "Adams", "Allen", "Anderson", "Armstrong", "Arnold", "Atkinson", "Austin", "Bailey", "Baker", "Banks", "Barnes", "Bell", "Bennett", "Bishop", "Black", "Boone", "Bowen", "Bradley", "Brooks", "Brown", "Bryant", "Burke", "Burns", "Butler", "Campbell", "Carlson", "Carpenter", "Carr", "Carter", "Chambers", "Chapman", "Clark", "Coleman", "Collins", "Cook", "Cooper", "Cox", "Crawford", "Cross", "Cruz", "Daniels", "Davidson", "Dawson", "Day", "Dean", "Diaz", "Dixon", "Douglas", "Doyle", "Duncan", "Dunn", "Edwards", "Elliott", "Ellis", "Evans", "Farmer", "Ferguson", "Fernandez", "Fields", "Fisher", "Fitzgerald", "Fleming", "Fletcher", "Flores", "Ford", "Foster", "Fowler", "Fox", "Francis", "Franklin", "Freeman", "Garcia", "Gardner", "Garrett", "George", "Gibson", "Gilbert", "Gomez", "Gonzalez", "Gordon", "Graham", "Grant", "Gray", "Green", "Griffin", "Gutierrez", "Hall", "Hamilton", "Hansen", "Harrison", "Hart", "Hawkins", "Hayes", "Henderson", "Henry", "Hernandez", "Hicks", "Hoffman", "Holland", "Holmes", "Hopkins", "Howard", "Hudson", "Hughes", "Hunter", "Ingram", "Jackson", "James", "Jenkins", "Jennings", "Jensen", "Jimenez", "Johns", "Johnson", "Jones", "Jordan", "Keller", "Kelly", "Kennedy", "Kim", "King", "Klein", "Knight", "Lambert", "Lane", "Larson", "Lawrence", "Lawson", "Lee", "Leonard", "Lewis", "Long", "Lopez", "Love", "Lowe", "Lucas", "Lynch", "Marshall", "Martinez", "Mason", "Matthews", "May", "McCarthy", "McDonald", "McGee", "McKenzie", "Medina", "Mendoza", "Meyer", "Miller", "Mitchell", "Montgomery", "Moore", "Morales", "Morgan", "Morris", "Morrison", "Murphy", "Murray", "Myers", "Nelson", "Newman", "Newton", "Nichols", "Nixon", "Norton", "Obrien", "Oliver", "Olson", "Ortega", "Owens", "Palmer", "Parker", "Parsons", "Patel", "Patterson", "Perez", "Perry", "Peters", "Peterson", "Phillips", "Porter", "Powell", "Price", "Ramirez", "Reed", "Reese", "Reid", "Reyes", "Reynolds", "Rice", "Richardson", "Riley", "Rivera", "Robbins", "Roberts", "Robertson", "Robinson", "Rodgers", "Rodriguez", "Rogers", "Romero", "Rose", "Ross", "Ruiz", "Russell", "Ryan", "Salazar", "Sanchez", "Sanders", "Schmidt", "Scott", "Sharp", "Shaw", "Shelton", "Silva", "Simmons", "Simpson", "Smith", "Snyder", "Sparks", "Spencer", "Stanley", "Steele", "Stephens", "Stevens", "Stewart", "Stone", "Strickland", "Sullivan", "Summers", "Taylor", "Terry", "Thomas", "Thompson", "Thornton", "Todd", "Torres", "Townsend", "Tucker", "Turner", "Valdez", "Vargas", "Vasquez", "Vaughn", "Wade", "Wagner", "Walker", "Wallace", "Walsh", "Ward", "Warren", "Washington", "Waters", "Watson", "Weaver", "Webb", "Weber", "Welch", "West", "Wheeler", "White", "Wilkins", "Williams", "Williamson", "Willis", "Wilson", "Wolfe", "Wong", "Wood", "Wright", "Wyatt", "Young", "Zamora", "Zimmerman",
  
    // Hispanic/South American Last Names
    "García", "Rodríguez", "González", "Hernández", "López", "Martínez", "Pérez", "Sánchez", "Ramírez", "Torres", "Flores", "Rivera", "Gómez", "Díaz", "Reyes", "Morales", "Ortiz", "Castro", "Gutiérrez", "Silva", "Mendoza", "Ruiz", "Álvarez", "Vargas", "Romero", "Jiménez", "Moreno", "Medina", "Cruz", "Rojas", "Herrera", "Chávez", "Aguilar", "Castillo", "Santos", "Fernández", "Núñez", "Paredes", "Ramos", "Vega", "Molina", "Delgado", "Cabrera", "Soto", "Guerrero", "Suárez", "Acosta", "Navarro", "Cordero", "Salazar", "Peña", "Cortés", "Campos", "Blanco", "Rivas", "León", "Marín", "Vásquez", "Muñoz", "Domínguez", "Iglesias", "Miranda", "Arias", "Mejía", "Bravo", "Vidal", "Sandoval", "Fuentes", "Franco", "Maldonado", "Contreras", "Espinoza", "Ríos", "Calderón", "Ponce", "Salinas", "Benítez", "Méndez", "Carrasco", "Estrada", "Solís", "Valencia", "Orellana", "Araya", "Cáceres", "Escobar", "Guzmán", "Valenzuela", "Cárdenas", "Lara", "Bustos", "Ferrer", "Villalobos", "Uribe", "Sepúlveda", "Hidalgo", "Moya", "Serrano", "Vergara", "Ortega",
  
    // German Last Names
    "Müller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Schulz", "Hoffmann", "Schäfer", "Koch", "Bauer", "Richter", "Klein", "Wolf", "Schröder", "Neumann", "Schwarz", "Zimmermann", "Braun", "Krüger", "Hofmann", "Hartmann", "Lange", "Schmitt", "Werner", "Schmitz", "Krause", "Meier", "Lehmann", "Schmid", "Schulze", "Maier", "Köhler", "Herrmann", "König", "Walter", "Mayer", "Huber", "Kaiser", "Fuchs", "Peters", "Lang", "Scholz", "Möller", "Weiß", "Jung", "Hahn", "Schubert", "Vogel", "Friedrich", "Keller", "Günther", "Frank", "Berger", "Winkler", "Roth", "Baum", "Sauer", "Wolff", "Pfeiffer", "Kuhn", "Otto", "Engel", "Horn", "Busch", "Bergmann", "Thomas", "Voigt", "Sander", "Kramer", "Graf", "Dietrich", "Seidel", "Lorenz", "Böhm", "Winter", "Schumacher", "Gross", "Krämer", "Jäger", "Sommer", "Haas", "Brandt", "Schuster", "Simon", "Stein", "Vogt", "Ludwig", "Kraft", "Franz", "Hansen", "Beyer", "Arnold", "Heinrich", "Barth",
  
  ];
  
  //For combining first and last, creating distinct arrays is better.
  module.exports = { firstNames, lastNames };