// Contains person name lists
const maleFirstNames = [
    "Aaron", "Adam", "Adrian", "Aiden", "Alan", "Albert", "Alex", "Alexander", "Andrew", "Anthony", "Arthur", "Austin", "Barry", "Benjamin", "Bernard", "Blake", "Bradley", "Brandon", "Brian", "Brody", "Bruce", "Bryan", "Caleb", "Cameron", "Carl", "Carlos", "Carter", "Chad", "Charles", "Christian", "Christopher", "Clarence", "Clifford", "Colin", "Colton", "Connor", "Craig", "Daniel", "David", "Declan", "Dennis", "Derek", "Derrick", "Dominic", "Donald", "Douglas", "Dylan", "Edward", "Eli", "Elijah", "Eric", "Erik", "Ethan", "Eugene", "Evan", "Felix", "Francis", "Frank", "Frederick", "Gabriel", "Gage", "Garrett", "Gary", "George", "Gerald", "Giovanni", "Grant", "Gregory", "Harold", "Hayden", "Henry", "Herbert", "Howard", "Hudson", "Hunter", "Ian", "Isaac", "Isaiah", "Ivan", "Jack", "Jackson", "Jacob", "Jake", "James", "Jared", "Jason", "Jasper", "Jayden", "Jeffrey", "Jeremiah", "Jeremy", "Joel", "John", "Johnny", "Jonathan", "Jordan", "Joseph", "Joshua", "Juan", "Julian", "Justin", "Keith", "Kenneth", "Kevin", "Kurt", "Kyle", "Landon", "Lawrence", "Leo", "Leonard", "Liam", "Logan", "Lucas", "Luis", "Luke", "Marcus", "Mark", "Marshall", "Martin", "Mason", "Matthew", "Michael", "Miguel", "Miles", "Morgan",  "Nathan", "Nathaniel", "Neil", "Nicholas", "Noah", "Nolan", "Norman", "Oliver", "Omar", "Oscar", "Owen", "Patrick", "Paul", "Peter", "Philip", "Preston", "Quentin", "Quincy", "Quinn", "Ralph", "Randall", "Raymond", "Reese", "Richard", "Riley", "Robert", "Robin", "Roger", "Ronald", "Ross", "Russell", "Ryan", "Samuel", "Scott", "Sean", "Sebastian", "Seth", "Shane", "Shawn", "Simon", "Spencer", "Stanley", "Stephen", "Steven", "Stuart", "Taylor", "Theodore", "Thomas", "Timothy", "Todd", "Travis", "Trevor", "Tristan", "Troy", "Tyler", "Tyson", "Victor", "Vincent", "Walter", "Warren", "Wayne", "Wesley", "William", "Wyatt", "Xander", "Xavier", "Zachary", "Zane",
    "Alejandro", "Mateo", "Santiago", "Matias", "Diego", "Emiliano", "Sebastian", "Joaquin", "Joaquín", "Daniel", "Nicolas", "Samuel", "Thiago", "Benjamín", "Leonardo", "Gabriel", "Lucas", "Tomas", "Martin", "Felipe", "David", "Juan Pablo", "Francisco", "Bruno", "Angel", "Alex", "Javier", "Manuel", "Ricardo", "Antonio", "Jorge", "Pedro", "Luis", "Carlos", "Miguel", "Rafael", "Jose", "Jesus", "Pablo", "Eduardo", "Arturo", "Fernando", "Raul", "Ramon", "Enrique", "Sergio", "Andrés", "Óscar", "Gustavo", "Roberto", "Hector",
    "Maximilian", "Alexander", "Paul", "Elias", "Felix", "Henry", "Louis", "Lukas", "Jonas", "Leon", "Noah", "Tim", "Finn", "Julian", "Ben", "Tom", "Niklas", "Jakob", "David", "Jan", "Philipp", "Maxim", "Fabian", "Matteo", "Anton", "Moritz", "Simon", "Jonathan", "Oscar", "Erik", "Johannes", "Frederik", "Leonard", "Vincent", "Karl", "Theodor", "Jannik", "Constantin", "Valentin", "Mika", "Florian", "Arthur", "Emil", "Julius", "Adrian", "Benedikt", "Richard", "Oskar",
  ];
  
  const femaleFirstNames = [
    // English/Caucasian Female First Names
    "Abigail", "Alexandra", "Alice", "Alicia", "Allison", "Alyssa", "Amanda", "Amber", "Amelia", "Amy", "Andrea", "Angela", "Angelina", "Anna",  "Ashley", "Aubrey", "Autumn", "Ava", "Avery", "Barbara", "Beth", "Beverly", "Bianca", "Brenda", "Brianna", "Brittany", "Brooke", "Carol", "Caroline", "Cassandra", "Catherine", "Cecilia",  "Charlotte", "Cheryl", "Christine",  "Claire", "Clara",  "Courtney", "Crystal", "Cynthia", "Danielle", "Deborah", "Delilah", "Diana", "Diane", "Donna", "Doris", "Dorothy", "Elaine", "Eleanor", "Elena",  "Eliza", "Elizabeth", "Ella", "Ellen", "Ellie", "Emily", "Emma", "Erica", "Erin", "Evelyn", "Faith", "Felicia", "Fiona", "Gabriella", "Georgia", "Gina", "Grace", "Gwendolyn", "Hannah", "Heather", "Holly", "Isabella", "Isabelle", "Ivy", "Jacqueline", "Jade", "Jamie", "Jasmine", "Jenna", "Jennifer",  "Jessica", "Jill", "Joan", "Joanna", "Jocelyn",  "Jordan", "Joyce", "Judith", "Judy", "Julia", "Julie", "Kaitlyn", "Karen", "Katherine", "Kathleen", "Katie", "Kayla", "Kelly", "Kimberly",  "Laura", "Lauren", "Leah",  "Leslie", "Lillian", "Lily", "Linda",  "Lucy", "Lydia", "Madeline", "Madison", "Makayla", "Margaret", "Maria", "Mariah", "Marie", "Marilyn",  "Martha", "Mary", "Megan", "Melanie", "Melissa", "Michelle", "Mikayla", "Miriam", "Molly", "Monica","Nancy", "Naomi", "Natalie",  "Nicole", "Nina",  "Nora", "Olivia", "Paige", "Pamela", "Patricia",  "Paula", "Penelope",  "Phoebe", "Priscilla", "Rachel", "Rebecca", "Regina",  "Riley", "Robin", "Rose", "Ruth",  "Samantha",  "Sandra", "Sara", "Sarah", "Savannah",  "Selena", "Serena",  "Shelby", "Shirley", "Sierra", "Sophia", "Stephanie",  "Susan", "Sydney", "Tessa", "Theresa", "Tina", "Tracy",  "Valerie", "Vanessa", "Veronica", "Victoria", "Violet", "Virginia", "Willow", "Yasmin", "Yvette","Zoe",
     "Sofia",  "Isabella",  "Valentina", "Camila", "Valeria",  "Renata",  "Antonella",  "Mariana",   "Gabriela", "Luciana",  "Ximena",  "Martina", "Catalina",  "Emma",   "Emilia",  "Victoria",  "Julieta", "Agustina",  "Josefina",  "Mia", "Florencia", "Abril",  "Zoe", "Paulina",  "Elena",  "Guadalupe",  "Andrea",   "Fernanda", "Daniela",  "Paola", "Adriana",  "Alejandra",  "Natalia",  "Isabel", "Maria", "Ana", "Carmen",  "Rosa", "Teresa",  "Patricia", "Martha",  "Monica", "Laura",  "Sandra", "Lucía",  "Lorena",  "Silvia", "Gloria", "Cristina",
      "Sophie", "Marie",  "Leonie", "Anna",  "Lena",  "Mia", "Emilia", "Johanna",  "Clara", "Emma",  "Hannah",  "Lina", "Sophia", "Mila", "Lara", "Ella", "Lisa", "Greta",  "Maja", "Frieda", "Hanna",  "Mathilda", "Amelie", "Ida",  "Luisa", "Sarah",  "Mara", "Julia",  "Leni", "Lilly",  "Paula", "Jana",  "Laura", "Elisa",  "Emily", "Melina", "Alina",  "Charlotte", "Mira",  "Helena", "Josephine", "Isabella", "Marlene",  "Eva",
  ];
  
  const lastNames = [
    "Adams", "Allen", "Anderson", "Armstrong", "Arnold", "Atkinson", "Austin", "Bailey", "Baker", "Banks", "Barnes", "Bell", "Bennett", "Bishop", "Black", "Boone", "Bowen", "Bradley", "Brooks", "Brown", "Bryant", "Burke", "Burns", "Butler", "Campbell", "Carlson", "Carpenter", "Carr", "Carter", "Chambers", "Chapman", "Clark", "Coleman", "Collins", "Cook", "Cooper", "Cox", "Crawford", "Cross", "Cruz", "Daniels", "Davidson", "Dawson", "Day", "Dean", "Diaz", "Dixon", "Douglas", "Doyle", "Duncan", "Dunn", "Edwards", "Elliott", "Ellis", "Evans", "Farmer", "Ferguson", "Fernandez", "Fields", "Fisher", "Fitzgerald", "Fleming", "Fletcher", "Flores", "Ford", "Foster", "Fowler", "Fox", "Francis", "Franklin", "Freeman", "Garcia", "Gardner", "Garrett", "George", "Gibson", "Gilbert", "Gomez", "Gonzalez", "Gordon", "Graham", "Grant", "Gray", "Green", "Griffin", "Gutierrez", "Hall", "Hamilton", "Hansen", "Harrison", "Hart", "Hawkins", "Hayes", "Henderson", "Henry", "Hernandez", "Hicks", "Hoffman", "Holland", "Holmes", "Hopkins", "Howard", "Hudson", "Hughes", "Hunter", "Ingram", "Jackson", "James", "Jenkins", "Jennings", "Jensen", "Jimenez", "Johns", "Johnson", "Jones", "Jordan", "Keller", "Kelly", "Kennedy", "Kim", "King", "Klein", "Knight", "Lambert", "Lane", "Larson", "Lawrence", "Lawson", "Lee", "Leonard", "Lewis", "Long", "Lopez", "Love", "Lowe", "Lucas", "Lynch", "Marshall", "Martinez", "Mason", "Matthews", "May", "McCarthy", "McDonald", "McGee", "McKenzie", "Medina", "Mendoza", "Meyer", "Miller", "Mitchell", "Montgomery", "Moore", "Morales", "Morgan", "Morris", "Morrison", "Murphy", "Murray", "Myers", "Nelson", "Newman", "Newton", "Nichols", "Nixon", "Norton", "Obrien", "Oliver", "Olson", "Ortega", "Owens", "Palmer", "Parker", "Parsons", "Patel", "Patterson", "Perez", "Perry", "Peters", "Peterson", "Phillips", "Porter", "Powell", "Price", "Ramirez", "Reed", "Reese", "Reid", "Reyes", "Reynolds", "Rice", "Richardson", "Riley", "Rivera", "Robbins", "Roberts", "Robertson", "Robinson", "Rodgers", "Rodriguez", "Rogers", "Romero", "Rose", "Ross", "Ruiz", "Russell", "Ryan", "Salazar", "Sanchez", "Sanders", "Schmidt", "Scott", "Sharp", "Shaw", "Shelton", "Silva", "Simmons", "Simpson", "Smith", "Snyder", "Sparks", "Spencer", "Stanley", "Steele", "Stephens", "Stevens", "Stewart", "Stone", "Strickland", "Sullivan", "Summers", "Taylor", "Terry", "Thomas", "Thompson", "Thornton", "Todd", "Torres", "Townsend", "Tucker", "Turner", "Valdez", "Vargas", "Vasquez", "Vaughn", "Wade", "Wagner", "Walker", "Wallace", "Walsh", "Ward", "Warren", "Washington", "Waters", "Watson", "Weaver", "Webb", "Weber", "Welch", "West", "Wheeler", "White", "Wilkins", "Williams", "Williamson", "Willis", "Wilson", "Wolfe", "Wong", "Wood", "Wright", "Wyatt", "Young", "Zamora", "Zimmerman",
    "García", "Rodríguez", "González", "Hernández", "López", "Martínez", "Pérez", "Sánchez", "Ramírez", "Torres", "Flores", "Rivera", "Gómez", "Díaz", "Reyes", "Morales", "Ortiz", "Castro", "Gutiérrez", "Silva", "Mendoza", "Ruiz", "Álvarez", "Vargas", "Romero", "Jiménez", "Moreno", "Medina", "Cruz", "Rojas", "Herrera", "Chávez", "Aguilar", "Castillo", "Santos", "Fernández", "Núñez", "Paredes", "Ramos", "Vega", "Molina", "Delgado", "Cabrera", "Soto", "Guerrero", "Suárez", "Acosta", "Navarro", "Cordero", "Salazar", "Peña", "Cortés", "Campos", "Blanco", "Rivas", "León", "Marín", "Vásquez", "Muñoz", "Domínguez", "Iglesias", "Miranda", "Arias", "Mejía", "Bravo", "Vidal", "Sandoval", "Fuentes", "Franco", "Maldonado", "Contreras", "Espinoza", "Ríos", "Calderón", "Ponce", "Salinas", "Benítez", "Méndez", "Carrasco", "Estrada", "Solís", "Valencia", "Orellana", "Araya", "Cáceres", "Escobar", "Guzmán", "Valenzuela", "Cárdenas", "Lara", "Bustos", "Ferrer", "Villalobos", "Uribe", "Sepúlveda", "Hidalgo", "Moya", "Serrano", "Vergara", "Ortega",
    "Müller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Schulz", "Hoffmann", "Schäfer", "Koch", "Bauer", "Richter", "Klein", "Wolf", "Schröder", "Neumann", "Schwarz", "Zimmermann", "Braun", "Krüger", "Hofmann", "Hartmann", "Lange", "Schmitt", "Werner", "Schmitz", "Krause", "Meier", "Lehmann", "Schmid", "Schulze", "Maier", "Köhler", "Herrmann", "König", "Walter", "Mayer", "Huber", "Kaiser", "Fuchs", "Peters", "Lang", "Scholz", "Möller", "Weiß", "Jung", "Hahn", "Schubert", "Vogel", "Friedrich", "Keller", "Günther", "Frank", "Berger", "Winkler", "Roth", "Baum", "Sauer", "Wolff", "Pfeiffer", "Kuhn", "Otto", "Engel", "Horn", "Busch", "Bergmann", "Thomas", "Voigt", "Sander", "Kramer", "Graf", "Dietrich", "Seidel", "Lorenz", "Böhm", "Winter", "Schumacher", "Gross", "Krämer", "Jäger", "Sommer", "Haas", "Brandt", "Schuster", "Simon", "Stein", "Vogt", "Ludwig", "Kraft", "Franz", "Hansen", "Beyer", "Arnold", "Heinrich", "Barth",
  ];
  
  module.exports = {
    maleFirstNames,
    femaleFirstNames,
    lastNames
  };